### ISSUE TITLE
Does your code work for long term result?

### ISSUE THREAD

**Issue by Jami1141** [vub-dl/u-cmab#1]
Hi,
I am new to use multi-arm bandit for my data. Recently, we did an A/B testing on some data to see how people convert if we contact them (group A) and don't contact them (Group B).
Now we are thinking to do a new test but not A/B testing but using multi arm-bandit. The problem is that If we call a person after 6 month we can find out how students converted. Multi-arm-bandit works for long term as well since we don't know yet the results?
I am using data including treatment (call or not) and outcome (converted or not). I want to do better way than A/B testing to find better choice with time but since our results will come after 6 month, I am not sure how to use that.
We were thinking for active-learning, which using A/B testing data, train our models separately for Model A and model B and then the subtraction between conversion probability of ModelA and ModelB for each student gives us uplift. Then now we want to do a new A/B testing for those students that their difference probability between Model A and Model B was low. But to do that we should wait for 6 month to see how students react to call. Is there a way to use multi arm bandit way for such long term obtained results? Is it possible to use your code? If yes how can I do it?
For example setting aside a portion of data for testing?

Many thanks in advance,

**Comment by jeroenbe** [comment]
Dear Jami1441,

A couple of extra questions:
1. between applying your treatment and registering an outcome, you you do other stuff also? I.e., are you applying more treatments in between?
2. Is the time aspect important, between your treatment and outcome important? Are you in anyway optimising this time? Is a shorter time respons better?

Regarding 2 models, there is some work on just training two models but we found them to perform rather poorly as they seem to introduce much variance in your outcomes (there is a paper by Devriendt et al. 2018 that might offer some insight).

Regarding bandits and a long waiting time; I would try to learn your policy offline for this. Usually, bandits are not used for a large time-gap. Try looking into papers on logged bandit feedback.

Hope this helps.
Jeroen

**Comment by Jami1141** [comment]
Dear jenoenbe,

 jenoenbe: A couple of extra questions:
 jenoenbe: between applying your treatment and registering an outcome, you you do other stuff  jenoenbe: also? I.e., are you applying more treatments in between?

jami1141:  In this case, suppose student registered in the university today. 10 days later our coaching team coach them. coaching is treatment. When we coach this student, we should wait for 6 month to see if student stay in to university or drop out. We want to see the effect of coaching on whether student stay or drop out.

We wait 6 month to know how they stay or drop out because of following:
We had some data at the beginning. We decided to do an A/B testing on this data. half of them randomly coached and half of them were not coached and we keep them as control group.
Then as I mentioned, we separately trained a model using group A (coached ones)  and group B (control group). Our model separately gives us stay probability. Since we trained two codes using two samples, If we have new student, we can give the feature of new student to each model.
Then stay probability of that student using model A minus stay probability of model B gives us an uplift fr that student.
If uplift is positive we recommend that student to be coached and if uplift is negative, we recommend that student to not to be coached.
Note: Since we trained our model, we assumed that we consider those students who dropped out before first semester (6 month). 
Now what we want o do: suppose each day we have some new students. we put them in model A and model B and calculate uplift for each student. Those uplifts who has low values around 0 positive or negative, are group that are not safe for us. 
Our plan is to redo an A/B testing for this sample of students that their uplift is very small around zero.
To do A/B testing we should have a enough size sample. Therefore every day we randomly assign some students as group A and some in group B and then we coach group A daily. After maybe 2 or 3 months that our sample size is enough, then we retrain our models using new A/B sample.

But since we have to wait for first, collecting enough size of data and second, we have to wait for 6 months for results, then we have to wait many month to see the results.

I want to see If there is a method instead of using reward (feedback) we can do multi-armed-bandit.

This was an example. I may have another project that I have three treatments (three products) and I want to use multi-armed-bandit instead of A/B testing. It is more important in this case for me the reward (gain) that company gets (dynamic discounting). 


 jenoenbe: Is the time aspect important, between your treatment and outcome important? Are you in anyway optimising this time? Is a shorter time respons better?

jami1141: For me If there is a way that I can optimise my products (dynamic discounting) to know which products is the best will be great.
For example company offer ipad, ipad + 1000 euros and ipad + 2000 euros to student. They do this offer by sending randomly email to leads. For us is important to see how leads converted based on  treatments. I used causallift model, which gives uplift for each lead. They randomly sent the email. I want to know If we have additional offers then without A/B testing and waiting until leads open their emails and based on that they convert or not take time. I am searching for delayed feedback. I see that Thompson sampling does not need immediate feedback.
But still is not clear for me is it really does not need reward?

**Comment by jeroenbe** [comment]
Hi Jami1141,

Your setup seems perfect to use uplift modelling or individual-treatment-effect modelling. 

To cope with this long timescale, I would pre-train a model using a logged bandit feedback -> that is, using some experience-replay as we did in [our paper](https://arxiv.org/abs/1910.07265). And then keep on training when new data arrives. That is, when you have the individual, treatment, and respons (x, t, y), you would update the model accordingly.

Does that make sense?
Jeroen

**Comment by Jami1141** [comment]
@jeroenbe 
 May I ask you to please explain a bit in more detailes about pre-train a model using a logged bandit feedback?
